project:
  type: website

  render:
    - Main_Analysis.qmd
    - 01-test.chapter.qmd

editor:
  markdown:
    references:
      location: block

format: 
    html:
      theme: minty
      code-fold: true
      highlight-style: arrow
      code-line-numbers: true
      code-copy: true
      df-print: paged
      highlight: default
      toc: true
      toc-depth: 5
      toc-title: Contents
      toc-location: left
      embed-resources: true
      output-ext: "html"



website:
  title: "Test Report"
  sidebar:
    logo: ./src/style/src/images/CRICK_Logotype_black_RGB.jpg
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - file: Main_Analysis.html
            text: "Analysis Overview"
          - section: "Test"
            contents:
              - file: testQC.html
                text: "Test QC"
          - section: "Main Test"
            contents:
              - file: 01-test.chapter.html
                text: "Test Chapter"





